version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.11

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:12.9.1-browsers

jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .
  install_dependencies:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  test:
    <<: *defaults
    resource_class: large
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Run tests
          command: npm run test

  build:
    <<: *defaults
    resource_class: large
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Build website
          command: npm run build
      - store_artifacts:
          path: ./build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./build

  deploy:
    <<: *defaults
    parameters:
      bucket_url:
        type: env_var_name
    steps:
      - attach_workspace:
          at: ~/repo
      - aws-s3/sync:
          from: ./build
          to: ${<< parameters.bucket_url >>}
          overwrite: true
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"

workflows:
  build-and-deploy:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - test:
          requires:
            - install_dependencies
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - develop
                - master
      - deploy:
          name: deploy_develop
          bucket_url: S3_BUCKET_URL_DEV
          context: oneleif-aws
          requires:
            - build
          filters:
            branches:
              only: develop
      - deploy:
          name: deploy_propuction
          bucket_url: S3_BUCKET_URL_PROD
          context: oneleif-aws
          requires:
            - build
          filters:
            branches:
              only: master
